name: Deploy to Firebase Hosting on merge

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # Service account JSON'u kullanarak kimlik doğrulama
      - name: Authenticate with service account
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DOSYA_TAKIP_SISTEMI_888BB }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcloud.json
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > "$GOOGLE_APPLICATION_CREDENTIALS"
          curl -sL https://firebase.tools | bash

      # Sabit proje ID'siyle deploy (yanlış projeye gitme riski yok)
      - name: Deploy to Firebase Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcloud.json
        run: |
          npx firebase deploy --only hosting --non-interactive --force \
            --project dosya-takip-sistemi-888bb
