name: Deploy to Firebase Hosting on merge

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@latest

      - name: Clear Firebase cache
        run: rm -rf "$HOME/.cache/firebase"

      - name: Authenticate with service account
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DOSYA_TAKIP_SISTEMI_888BB }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > "$HOME/gcloud.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json" >> "$GITHUB_ENV"

      - name: Deploy to Firebase Hosting
        run: |
          firebase experiments:enable webframeworks
          firebase deploy --only hosting --non-interactive --force \
            --project dosya-takip-sistemi-888bb --debug
